### ISSUE TITLE
Also support HTTP conneg for RDF download

### ISSUE THREAD

**Issue by dr-shorthair** [ckan/ckanext-dcat#119]
RDF download is described here: https://github.com/ckan/ckanext-dcat#rdf-dcat-endpoints 
The support for the various serializations is good, denoted by file-type suffixes. 
But it appears that HTTP conneg is not supported? 
I get HTML regardless of the value of the Accept: header (tested using PostMan).

**Comment by amercader** [comment]
@dr-shorthair Content negotiation is indeed supported, but due to the nature of the implementation it needs to be enabled on the CKAN instance with the following setting:

    ckanext.dcat.enable_content_negotiation = True

I've now enable it on demo.ckan.org, so you can try:

    curl https://demo.ckan.org -H Accept:text/turtle

All details [here](https://github.com/ckan/ckanext-dcat#content-negotiation), please feel free to reopen if you find any issue.
