### ISSUE TITLE
DCAT Profile Support

### ISSUE THREAD

**Issue by philipashlock** [ckan/ckanext-dcat#13]
Does this support DCAT profiles? For example, can you validate a harvest source against a DCAT profile that defines certain required fields?

It looks like there's some documentation for a Europe-wide DCAT profile at:
https://joinup.ec.europa.eu/asset/dcat_application_profile/asset_release/dcat-application-profile-data-portals-europe-final

**Comment by neothemachine** [comment]
This would be useful for the "spatial" and "temporal" fields which are more clearly defined in the [GeoDCAT-AP](https://joinup.ec.europa.eu/node/139283/) profile currently being developed. Is there any handling of those two fields in the harvester currently?

**Comment by tryggvib** [comment]
@amercader has this issue been solved with #19 ?

**Comment by amercader** [comment]
@philipashlock Work on DCAT profiles started as part of #19 (ingesting RDF) and will be finished with #28 (producing RDF). The base profile is based on the European DCAT-AP, but it should be generic enough for most cases.

@neothemachine @tryggvib  There is the following support for the temporal field:

https://github.com/ckan/ckanext-dcat/blob/43af079b0dd97b97bbc5279b9c79a3df762595e6/ckanext/dcat/profiles.py#L110

This essentially supports temporal intervals defined with both schema.org `startDate` & `endDate` and W3C Time `hasBeginning` & `hasEnd`.

As for the spatial field, as there wasn't a clear convention on how to define it, for now the base parser will just extract an URI for the spatial field, and is left to the specific profiles to extract more detailed information (as in [this example](https://github.com/okfn/ckanext-sweden/blob/9f8d1fce7e9b46d7db4e901e5bab411ccfa532b5/ckanext/sweden/dcat/profiles.py)).
As part of the remaining work on #28 I'm really keen on better supporting the spatial field. If GeoDCAT-AP provides a clear guidance on how to do that, that would be fantastic. It looks like it's still a work in progress though, @neothemachine do you know the status of this and how safe it is to use it as guidance? I'm also not sure if that covers complex geometries apart from bounding boxes.

**Comment by neothemachine** [comment]
@amercader I just recently started following the GeoDCAT-AP mailing list, but from what I see I think it is relatively safe to at least partially follow it. The draft defines spatial as being a bounding box only, which at a minimum must be given as either WKT or GML. With GML it is really a bounding box fixed by its XML structure, but with WKT it's just a polygon, so I'm sure as time comes this will lead to people putting more complex geometries as WKT polygon. I don't think anyone will use GML here to be honest.

The WKT form would be:
```
@prefix dct: <http://purl.org/dc/terms/> .
@prefix locn: <http://www.w3.org/ns/locn#> .
@prefix gsp: <http://www.opengis.net/ont/geosparql#> .

[] dct:spatial [ a dct:Location ;
    locn:geometry "POLYGON((-10.58 70.09,34.59 70.09,34.59 34.56,-10.58 34.56,-10.58 70.09))"^^gsp:wktLiteral 
   .]
```

I think this is sensible and will actually be used once the spec is complete. It integrates nicely with GeoSPARQL as well.

So my suggestion would be to follow the WKT route and implement simple bounding boxes for now, as this is what the spec says. Of course, if it's easy to implement support for arbitrary WKT polygons, go ahead, but I guess the majority will stick to bounding boxes.

**Comment by amercader** [comment]
Thanks @neothemachine that's useful. We'll see how it goes.

Cheers

**Comment by amercader** [comment]
Full documentation for the profiles support is here: https://github.com/ckan/ckanext-dcat#profiles

@neothemachine I ended up implementing the GeoDCAT-AP recommendation for the spatial field, you can see it in action here:

http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.xml
http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.ttl

**Comment by neothemachine** [comment]
Looks good, nice work! :)
