### ISSUE TITLE
Manage downloadURL or accessURL

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-dcat#2]
CKAN resources have just a single `url` property. We could rely on the resource type or format to decide if this is direct download.
For harvested datasets, we can probably store what kind of URL was defined and reuse it later on.

**Comment by etj** [comment]
Current code:

```
            resource_dict['url'] = (self._object_value(distribution,
                                                       DCAT.accessURL) or
                                    self._object_value(distribution,
                                                       DCAT.downloadURL))
```

Where:
- `accessURL` (1..n): This property contains a URL that gives access to a Distribution of the Dataset. The resource at the access URL may contain information about how to get the Dataset.
- `downloadURL`(0..n): This property contains a URL that is a direct link to a downloadable file in a given format.

So, `downloadURL` provides the real data (needed by any recline viewer), while `accessURL` is a generic page which provides access to the data.

I guess that **the assignment should be reversed**, so that if `downloadURL` is not defined, the `accessURL` is taken as fallback.
Also, since `accessURL` is mandatory, dataset created by valid DCAT data will never use the `downloadURL`.

**Comment by amercader** [comment]
@etj that makes sense, feel free to submit a PR!
