### ISSUE TITLE
DCAT and CKAN disagree on license location

### ISSUE THREAD

**Issue by pduchesne** [ckan/ckanext-dcat#42]
DCAT defines the license element as a Distribution property (i.e. part of a Resource in CKAN terms), but CKAN defines the license at the Dataset level.
This is a structural mismatch that's probably beyond the scope of this component, but it is still an issue in its usage. Can ckanext-dcat offer a pragmatic, workaround solution, like supporting a dct:license field on dcat:Dataset, or take the first license of a resource as the dataset license ?

**Comment by amercader** [comment]
I tried to avoid making assumptions when building the first version of the default profile but we can definitely start to be a bit more opinionated (within a limit :) ).

To me is a real shame that DCAT defines the license at the resource level, at least I wouldn't mind it if there was a Dataset level license that resources would inherit from (like the catalog one).

In any case, taking the first license of a resource and setting it on the dataset sounds good (we might have problems mapping the dcat values to the license_id values used by CKAN)

**Comment by pstarace** [comment]
This is exactly what we do on http://www.sciamlab.com/opendatahub/dataset since almost all the catalogs we are indexing define the license at dataset level. So as first we build a DCAT compliant model (CKAN independent) copying the same license to all the distributions and then we use the first from the list to populate CKAN. Doing so we don't loose any information. 
It would be different if a catalog would put a different license for distributions of the same dataset, but so far this has never happened in our experience (and this may let us reconsidering the correctness to place the license on a distribution level....).

**Comment by pduchesne** [comment]
Thanks Simon. Very informative.
