### ISSUE TITLE
Harvester picks random language

### ISSUE THREAD

**Issue by neothemachine** [ckan/ckanext-dcat#51]
I have a [JSON-LD DCAT catalog](https://github.com/ec-melodies/wp02-dcat/blob/master/WP2.jsonld) which includes translations for some strings (like the dataset title). The harvester seems to randomly pick any of those translations. I know that CKAN doesn't support [multilingual fields](https://github.com/ckan/ckan/issues/2678) yet, but then the harvester could at least pick the translation that matches the default language of the CKAN instance, and fall-back to a random choice if there's no match.

**Comment by amercader** [comment]
Agreed, see #55

**Comment by seitenbau-govdata** [comment]
Hi @amercader,
I think this is independent from #55, because we (in a first step) and some people do not need a full multilingual support and storing of the data (with the need installing ckanext-scheming), but only want to store the values in the default language if available.

We would like to create a pull request addressing this issue. In a first step only for the title and the description. We will take into account that the code changes are compatible as possible to #55.

What do you think?

**Comment by pduchesne** [comment]
Hello @seitenbau-govdata . We're having the exact same issue. If you have that PR ready, i'd be interested. Thanks.

**Comment by seitenbau-govdata** [comment]
Hi @pduchesne . We're still working on the PR. I think we could create the PR within the next two weeks. Cheers.
